[project]
name = "research-notebooks"
version = "0.1.0"
dependencies = [
    "jupyter",
    "matplotlib",
    "seaborn",
    "ml-core",
    "ipykernel>=7.1.0",
    "scikit-learn>=1.8.0",
]

[tool.uv.sources]
ml-core = { workspace = true }
